[build]
buildCommand = "npm i -g pnpm && pnpm install && pnpm --filter @travelrn/server exec prisma generate && pnpm --filter @travelrn/server build"

[deploy]
startCommand = "pnpm --filter @travelrn/server start"
