[build]
buildCommand = "npm install --include=dev && npx prisma generate --schema=apps/server/prisma/schema.prisma && npm run build --workspace=apps/server"

[deploy]
startCommand = "npm run start --workspace=apps/server"
restartPolicyType = "ON_FAILURE"
